USE [master]
CREATE DATABASE [AOPDemo]

USE [AOPDemo]
CREATE TABLE [dbo].[BOOKS](
	ID INT IDENTITY(1,1) NOT NULL,
	TITLE NVARCHAR(250) NULL,
	AUTHOR NVARCHAR(250) NULL,
	CONSTRAINT PK_BOOKS PRIMARY KEY(ID ASC)
)
